name: Build and update LaTeX PDF
on: [push]
permissions:
  contents: write
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: true

      - name: Rename PDF file
        run: mv main.pdf resume_viola.pdf

      - name: Commit and push updated PDF
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add resume_viola.pdf
          git commit -m "Update resume_viola.pdf"
          git push